import OpenAI from "openai";

import { SYSTEM_PROMPT } from "./prompts.js";
import { validateDecision } from "./validator.js";

import { searchPolicies } from "../services/policyService.js";
import { searchTickets, createTicket } from "../services/ticketService.js";
import { addAuditRecord } from "../services/auditService.js";

const client = process.env.GROQ_API_KEY
  ? new OpenAI({
      apiKey: process.env.GROQ_API_KEY,
      baseURL: "https://api.groq.com/openai/v1"
    })
  : null;

function getMessageText(message) {
  return message?.content || message?.text || "";
}

function buildConversationContext(conversation = []) {
  if (!Array.isArray(conversation) || conversation.length === 0) {
    return "";
  }

  return conversation
    .map((message) => {
      const role = message.role === "assistant" ? "Agent" : "User";
      return `${role}: ${getMessageText(message)}`;
    })
    .join("\n");
}

function buildSearchText(request, conversation) {
  return [
    request.subject,
    request.issue,
    request.description,
    buildConversationContext(conversation)
  ]
    .filter(Boolean)
    .join("\n");
}

function classifyFallback(request, conversation = []) {
  const conversationText = buildConversationContext(conversation);
  const currentText = [
    request.subject,
    request.issue,
    request.description
  ]
    .filter(Boolean)
    .join(" ");

  const text = `${currentText}\n${conversationText}`.toLowerCase();

  // Security / phishing
  if (
    text.includes("phishing") ||
    text.includes("malware") ||
    text.includes("unauthorized access") ||
    text.includes("suspicious email")
  ) {
    return {
      category: "Security",
      action: "ESCALATE",
      response:
        "This should be reported immediately to security@veridian-corp.example. The request has been escalated to Security.",
      policy_ids: ["KB-09"],
      historical_ticket_ids: ["TK-1048"],
      policy_interaction: "",
      createTicket: true
    };
  }

  // Contractor VPN
  if (text.includes("contractor") && text.includes("vpn")) {
    return {
      category: "VPN Access",
      action: "APPROVAL REQUIRED",
      response:
        "Contractors require manager approval via the access request form before VPN access can be provided.",
      policy_ids: ["KB-02"],
      historical_ticket_ids: [],
      policy_interaction: "",
      createTicket: true
    };
  }

  // VPN credentials and follow-up questions about renewal
  if (
    text.includes("vpn") &&
    (
      text.includes("expired") ||
      text.includes("credential") ||
      text.includes("renew") ||
      text.includes("renewal")
    )
  ) {
    return {
      category: "VPN",
      action: "RESOLVE",
      response:
        "Per KB-02, VPN credentials expire every 90 days and must be renewed by the employee. Full-time employees receive VPN access automatically.",
      policy_ids: ["KB-02"],
      historical_ticket_ids: ["TK-1042"],
      policy_interaction: "",
      createTicket: false
    };
  }

  // General VPN
  if (text.includes("vpn")) {
    return {
      category: "VPN",
      action: "FOLLOW UP",
      response:
        "VPN access is automatic for full-time employees. Contractors require manager approval via the access request form.",
      policy_ids: ["KB-02"],
      historical_ticket_ids: ["TK-1042"],
      policy_interaction: "",
      createTicket: true
    };
  }

  // Password
  if (
    text.includes("password") &&
    (
      text.includes("locked") ||
      text.includes("lockout") ||
      text.includes("failed")
    )
  ) {
    return {
      category: "Password Reset",
      action: "RESOLVE",
      response:
        "After 5 failed password attempts, IT manually unlocks the account. No approval is required.",
      policy_ids: ["KB-01"],
      historical_ticket_ids: ["TK-1049"],
      policy_interaction: "",
      createTicket: false
    };
  }

  if (text.includes("password")) {
    return {
      category: "Password Reset",
      action: "RESOLVE",
      response:
        "Use the self-service password reset portal. It is available anytime.",
      policy_ids: ["KB-01"],
      historical_ticket_ids: ["TK-1049"],
      policy_interaction: "",
      createTicket: false
    };
  }

  // Guest Wi-Fi
  if (
    text.includes("guest") &&
    (text.includes("wifi") || text.includes("wi-fi"))
  ) {
    return {
      category: "Guest Wi-Fi",
      action: "RESOLVE",
      response:
        "Guest Wi-Fi credentials are valid for 24 hours and can be generated by any employee at the front-desk kiosk. No IT ticket is required.",
      policy_ids: ["KB-07"],
      historical_ticket_ids: ["TK-1051"],
      policy_interaction: "",
      createTicket: false
    };
  }

  // Non-catalog software
  if (
    text.includes("non-catalog") ||
    text.includes("not in the catalog")
  ) {
    return {
      category: "Software",
      action: "FOLLOW UP",
      response:
        "Non-catalog software requires IT Security review, which takes 3–5 business days.",
      policy_ids: ["KB-04"],
      historical_ticket_ids: ["TK-1044"],
      policy_interaction: "",
      createTicket: true
    };
  }

  // Browser extension
  if (
    text.includes("browser extension") ||
    text.includes("extension")
  ) {
    return {
      category: "Software",
      action: "FOLLOW UP",
      response:
        "If the browser extension is not in the software catalog, it requires IT Security review.",
      policy_ids: ["KB-04"],
      historical_ticket_ids: [],
      policy_interaction: "",
      createTicket: true
    };
  }

  // Printer
  if (text.includes("printer")) {
    return {
      category: "Printer",
      action: "FOLLOW UP",
      response:
        "Check the print queue and restart the print spooler. If the problem persists, create a ticket including the printer asset tag.",
      policy_ids: ["KB-05"],
      historical_ticket_ids: ["TK-1046"],
      policy_interaction: "",
      createTicket: true
    };
  }

  // Mailbox
  if (
    text.includes("mailbox") ||
    text.includes("email storage") ||
    text.includes("mail storage")
  ) {
    return {
      category: "Mailbox",
      action: "FOLLOW UP",
      response:
        "The default mailbox size is 25GB. Employees should archive old mail. Increases above 25GB require manager approval and cannot exceed 50GB.",
      policy_ids: ["KB-06"],
      historical_ticket_ids: ["TK-1045"],
      policy_interaction: "",
      createTicket: true
    };
  }

  // Expense software
  if (
    text.includes("expense") &&
    (
      text.includes("software") ||
      text.includes("tool") ||
      text.includes("login") ||
      text.includes("credential")
    )
  ) {
    return {
      category: "Expense Software",
      action: "FOLLOW UP",
      response:
        "Finance grants access to the expense software, not IT. IT handles login or technical issues once the account exists.",
      policy_ids: ["KB-08"],
      historical_ticket_ids: [],
      policy_interaction: "",
      createTicket: true
    };
  }

  // WFH equipment
  if (
    (
      text.includes("wfh") ||
      text.includes("work from home") ||
      text.includes("remote")
    ) &&
    (
      text.includes("monitor") ||
      text.includes("chair") ||
      text.includes("equipment")
    )
  ) {
    return {
      category: "WFH Equipment",
      action: "APPROVAL REQUIRED",
      response:
        "Employees working remotely more than 3 days/week are eligible for a one-time chair/monitor allowance. Manager sign-off and Finance processing are required. IT ships only after approval.",
      policy_ids: ["KB-10"],
      historical_ticket_ids: ["TK-1047"],
      policy_interaction: "",
      createTicket: true
    };
  }

  // Laptop / hardware
  if (
    text.includes("laptop") ||
    text.includes("screen") ||
    text.includes("hardware") ||
    text.includes("computer")
  ) {
    const hasThreeYears =
      text.includes("3 year") ||
      text.includes("3-year") ||
      text.includes("3.5") ||
      text.includes("3 years");

    const hasHardwareFailure =
      text.includes("dead") ||
      text.includes("not working") ||
      text.includes("failure") ||
      text.includes("flickering");

    if (hasThreeYears && hasHardwareFailure) {
      return {
        category: "Laptop Replacement",
        action: "APPROVAL REQUIRED",
        response:
          "KB-03 says laptops are eligible for replacement after 3 years or earlier for verified hardware failure. The Asset Management Policy uses a 4-year refresh cycle and requires Finance sign-off in addition to IT approval for early replacement outside that cycle.",
        policy_ids: ["KB-03", "ASSET-POLICY"],
        historical_ticket_ids: ["TK-1043"],
        policy_interaction:
          "KB-03 establishes eligibility after 3 years or earlier for verified hardware failure, while the Asset Management Policy establishes a 4-year refresh cycle and additional Finance sign-off for early replacement outside that cycle.",
        createTicket: true
      };
    }

    if (hasHardwareFailure) {
      return {
        category: "Laptop / Hardware",
        action: "FOLLOW UP",
        response:
          "KB-03 allows earlier laptop replacement for verified hardware failure. The replacement request should be evaluated against the applicable hardware policy.",
        policy_ids: ["KB-03", "ASSET-POLICY"],
        historical_ticket_ids: [],
        policy_interaction:
          "KB-03 and the Asset Management Policy may both apply to hardware replacement requests.",
        createTicket: true
      };
    }

    if (
      text.includes("4 year") ||
      text.includes("4-year") ||
      text.includes("4 years")
    ) {
      return {
        category: "Laptop Replacement",
        action: "FOLLOW UP",
        response:
          "The Asset Management Policy specifies a 4-year hardware refresh cycle from the date of issue.",
        policy_ids: ["ASSET-POLICY"],
        historical_ticket_ids: [],
        policy_interaction: "",
        createTicket: true
      };
    }
  }

  // Admin access
  if (
    text.includes("admin access") ||
    (text.includes("access") && text.includes("server"))
  ) {
    return {
      category: "Admin Access",
      action: "FOLLOW UP",
      response:
        "A historical admin-access request (TK-1050) was rejected because no business justification was provided. This historical ticket is precedent, not a separate policy.",
      policy_ids: [],
      historical_ticket_ids: ["TK-1050"],
      policy_interaction: "",
      createTicket: true
    };
  }

  // No grounded match
  return {
    category: "Clarification Needed",
    action: "CLARIFY",
    response:
      "I need a little more information before I can determine the applicable IT support path.",
    policy_ids: [],
    historical_ticket_ids: [],
    policy_interaction: "",
    createTicket: false
  };
}

async function callLLM(request, conversation = []) {
  if (!client) {
    return null;
  }

  const searchText = buildSearchText(request, conversation);
  const relevantPolicies = searchPolicies(searchText);
  const relevantTickets = searchTickets(searchText);
  const conversationText = buildConversationContext(conversation);

  const messages = [
    {
      role: "system",
      content: SYSTEM_PROMPT
    },
    ...conversation.map((message) => ({
      role: message.role === "assistant" ? "assistant" : "user",
      content: getMessageText(message)
    })),
    {
      role: "user",
      content: `
CURRENT REQUEST:
${JSON.stringify(request, null, 2)}

CONVERSATION CONTEXT:
${conversationText || "No previous conversation."}

RELEVANT POLICIES:
${JSON.stringify(relevantPolicies, null, 2)}

HISTORICAL TICKETS:
${JSON.stringify(relevantTickets, null, 2)}

Answer the current request using the conversation context and ONLY the supplied
Veridian source material.

Resolve follow-up references such as "it", "this", "that", "them", and "how do I
renew?" using the previous conversation when possible.

If the source material does not answer the requested detail, say that the supplied
material does not specify it. Do not invent a procedure.

Return ONLY valid JSON.
`
    }
  ];

  try {
    const completion = await client.chat.completions.create({
      model: process.env.GROQ_MODEL || "llama-3.1-8b-instant",
      temperature: 0,
      messages,
      response_format: { type: "json_object" }
    });

    const content = completion.choices?.[0]?.message?.content;

    if (!content) {
      return null;
    }

    return JSON.parse(content);
  } catch (error) {
    console.error("LLM unavailable:", error.message);
    return null;
  }
}

export async function analyzeRequest(request, conversation = []) {
  const searchText = buildSearchText(request, conversation);
  const matchedPolicies = searchPolicies(searchText);
  const matchedTickets = searchTickets(searchText);

  const replay = [
    {
      step: 1,
      label: "Request received",
      detail:
        request.issue ||
        request.description ||
        request.subject ||
        "No issue text provided"
    },
    {
      step: 2,
      label: "Relevant policies searched",
      detail:
        matchedPolicies.length
          ? matchedPolicies.map((policy) => policy.id).join(", ")
          : "No direct policy source identified"
    },
    {
      step: 3,
      label: "Historical tickets checked",
      detail:
        matchedTickets.length
          ? matchedTickets.map((ticket) => ticket.id).join(", ")
          : "No specific precedent used"
    }
  ];

  let decision = await callLLM(request, conversation);
  let mode = "ai";

  if (!validateDecision(decision)) {
    decision = classifyFallback(request, conversation);
    mode = "rules";
  }

  replay.push({
    step: 4,
    label: "Decision generated",
    detail: `${decision.category} → ${decision.action}`
  });

  let ticket = null;

  if (decision.createTicket) {
    ticket = createTicket(request, decision);
  }

  replay.push({
    step: 5,
    label: "Decision validated",
    detail:
      mode === "ai"
        ? "AI decision validated"
        : "Grounded rules used"
  });

  if (ticket) {
    replay.push({
      step: 6,
      label: "Ticket created",
      detail: ticket.id
    });
  }

  const audit = addAuditRecord({
    request_id: request.id,
    employee: request.employee,
    category: decision.category,
    action: decision.action,
    policy_ids: decision.policy_ids,
    historical_ticket_ids: decision.historical_ticket_ids,
    mode
  });

  return {
    request,
    ...decision,
    ticket,
    replay,
    audit,
    mode
  };
}
